PORTNAME=	arduino-serial-discovery
DISTVERSIONPREFIX=	v
DISTVERSION=	1.5.2
CATEGORIES=	devel

MAINTAINER=	pcc@gmx.net
COMMENT=	Serial port pluggable discovery tool for arduino-cli
WWW=		https://github.com/arduino/serial-discovery

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		go:modules
GO_MODULE=	github.com/arduino/serial-discovery

PLIST_FILES=	bin/arduino-serial-discovery

.include <bsd.port.mk>
