# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	pyactiveresource
PORTVERSION=	2.2.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Activeresource for python
WWW=		https://github.com/Shopify/pyactiveresource/

LICENSE=	MIT

INSTALL_DEPENDS=	${PYTHON_PKGNAMEPREFIX}six>0:devel/py-six@${PY_FLAVOR}

USES=		python:3.3+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
