PORTNAME=	arduino-mdns-discovery
DISTVERSIONPREFIX=	v
DISTVERSION=	1.1.0
CATEGORIES=	devel

MAINTAINER=	pcc@gmx.net
COMMENT=	mDNS pluggable discovery tool for arduino-cli
WWW=		https://github.com/arduino/mdns-discovery

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		go:modules
GO_MODULE=	github.com/arduino/mdns-discovery

PLIST_FILES=	bin/arduino-mdns-discovery

.include <bsd.port.mk>
