# Created by: Peter Cornelius <pcc@gmx.net>
# $FreeBSD$

PORTNAME=	rpi.gpio
PORTVERSION=	0.7.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	A module to control raspberry pi gpio channels

# LICENSE=	MIT # Ensure this is valid! See ${PORTSDIR}/Mk/bsd.licenses.db.mk.

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
