# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	nematode
PORTVERSION=	g20190614
CATEGORIES=	astro comms devel

MAINTAINER=	pcc@gmx.net
COMMENT=	Cross platform C++ 11 NMEA Parser & GPS Framework
WWW=		https://github.com/ckgt/NemaTode

LICENSE=	ZLIB

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	ckgt
GH_PROJECT=	NemaTode
GH_TAGNAME=	d061b62

.include <bsd.port.mk>
