# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	goocalendar
PORTVERSION=	0.8.0
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	GooCalendar-${DISTVERSIONPREFIX}${DISTVERSION}${DISTVERSIONSUFFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Calendar widget for gtk using pygoocanvas
WWW=		https://pypi.org/project/GooCalendar/

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.4+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
