#
OPTIONS_GROUP_QUALITY=	QUALITYFUNDAMENTAL
OPTIONS_DEFAULT+=	QUALITYFUNDAMENTAL
QUALITY_DESC=		Operational Modules - Manage Quality
QUALITYFUNDAMENTAL_DESC=	Fundamentals to manage quality.
QUALITYFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-quality=${PORTVERSION}:finance/py-trytond-quality@${PY_FLAVOR}
