#
OPTIONS_GROUP_ATTENCANCE=	ATTENDANCEFUNDAMENTAL
OPTIONS_DEFAULT+=	ATTENDANCEFUNDAMENTAL
ATTENDANCE_DESC=	Operational Modules - Track presences
ATTENDANCEFUNDAMENTAL_DESC=		Track presences.
ATTENDANCEFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-attendance>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-attendance@${PY_FLAVOR}
