#
OPTIONS_GROUP_CURRENCY=	CURRENCYFUNDAMENTAL ROMANIAN SERBIAN
OPTIONS_DEFAULT+=	CURRENCYFUNDAMENTAL
CURRENCY_DESC=		Referential Modules - Manage Currencies
CURRENCYFUNDAMENTAL_DESC=		ISO 4217 list of currencies.
CURRENCYFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-currency>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-currency@${PY_FLAVOR}
ROMANIAN_DESC=		Exchange rates from the Romanian National Bank.
ROMANIAN_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-currency-ro>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-currency-ro@${PY_FLAVOR}
SERBIAN_DESC=		Exchange rates from the Serbian National Bank.
SERBIAN_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-currency-rs>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-currency-rs@${PY_FLAVOR}
