#
OPTIONS_GROUP_SALEPOINT=	SALEPOINTFUNDAMENTAL
#OPTIONS_DEFAULT+=	# Not yet
SALEPOINT_DESC=		Operational Modules - Point of Sales
SALEPOINTFUNDAMENTAL_DESC=		Fundamentals for POS.
SALEPOINTFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-sale-point>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-sale-point@${PY_FLAVOR}
