#
OPTIONS_GROUP_ANALYTIC=	ANALYTICFUNDAMENTAL BUDGET ANALYTICINVOICE \
			ANALYTICPURCHASE ANALYTICSALE
OPTIONS_DEFAULT+=	ANALYTICFUNDAMENTAL
ANALYTIC_DESC=		Operational Modules - Analyze Your Accounts
ANALYTICFUNDAMENTAL_DESC=		Fundamentals for analytic.
ANALYTICFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-analytic-account>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-analytic-account@${PY_FLAVOR}
BUDGET_DESC=		Budgets for analytic accounts.
BUDGET_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-analytic-budget>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-analytic-budget@${PY_FLAVOR}
ANALYTICINVOICE_DESC=		Adds analytic on invoice.
ANALYTICINVOICE_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-analytic-invoice>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-analytic-invoice@${PY_FLAVOR}
ANALYTICPURCHASE_DESC=		Adds analytic on purchase.
ANALYTICPURCHASE_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-analytic-purchase>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-analytic-purchase@${PY_FLAVOR}
ANALYTICSALE_DESC=		Adds analytic on sale.
ANALYTICSALE_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-analytic-sale>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-analytic-sale@${PY_FLAVOR}
