#
OPTIONS_GROUP_COUNTRY=	COUNTRYFUNDAMENTAL
OPTIONS_DEFAULT+=	COUNTRYFUNDAMENTAL
COUNTRY_DESC=		Referential Modules - ISO 3166 List of Countries and Subdivisions
COUNTRYFUNDAMENTAL_DESC=	ISO 3166 list of countries and subdivisions.
COUNTRYFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-country>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-country@${PY_FLAVOR}
