#
OPTIONS_GROUP_COMMISSION=	COMMISSIONFUNDAMENTAL WAITING
OPTIONS_DEFAULT+=	COMMISSIONFUNDAMENTAL
COMMISSION_DESC=	Operational Modules - Commission Sales Agents
COMMISSIONFUNDAMENTAL_DESC=		Fundamentals to commission sales agents.
COMMISSIONFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-commission>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-commission@${PY_FLAVOR}
WAITING_DESC=		Creates waiting account moves.
WAITING_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-commission-waiting>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-commission-waiting@${PY_FLAVOR}
