#
OPTIONS_GROUP_GOOGLEMAPS=	GOOGLEMAPSFUNDAMENTAL
OPTIONS_DEFAULT+=	GOOGLEMAPSFUNDAMENTAL
GOOGLEMAPS_DESC=	Referential Modules - Link Address to Google Maps
GOOGLEMAPSFUNDAMENTAL_DESC=	Links address to Google map.
GOOGLEMAPSFUNDAMENTAL_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}trytond-google-maps>=${TRYTON_MIN_VERSION}<${TRYTON_MAX_VERSION}:finance/py-trytond-google-maps@${PY_FLAVOR}
