# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	pyopengl
PORTVERSION=	3.1.7
CATEGORIES=	x11 python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyOpenGL-${DISTVERSIONPREFIX}${DISTVERSION}${DISTVERSIONSUFFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Standard opengl bindings for python
WWW=		http://pyopengl.sourceforge.net/

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/license.txt

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
