#!/bin/sh

. /etc/rc.subr

name=tryton
rcvar=tryton_enable

start_cmd="${name}_start"
stop_cmd=":"

load_rc_config $name
: ${tryton_enable:=no}
: ${tryton_msg="Tryton not ready for use hence NOT started."}

dummy_start()
{
	echo "$dummy_msg"
}

run_rc_command "$1"
