# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	febelfin-coda
PORTVERSION=	0.3.0
CATEGORIES=	finance python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Module to parse coda files
WWW=		https://coda.b2ck.com/


LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

USES=		python:3.5+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
