# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	mt940
PORTVERSION=	0.6.0
CATEGORIES=	finance python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Module to parse mt940 files
WWW=		http://mt940.b2ck.com/

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

USES=		python:3.5+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
