# Created by: Peter Cornelius <pcc@gmx.net>

PORTNAME=	mt940
PORTVERSION=	0.6.0
CATEGORIES=	finance python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Module to parse mt940 files
WWW=		http://mt940.b2ck.com/

# setup.py just says 'BSD' so I guess it's the traditional 3-clause BSD licence'
LICENSE=	BSD3CLAUSE

USES=		python:3.5+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
