# Created by: Peter Cornelius <pcc@gmx.net>
# $FreeBSD$

PORTNAME=	pigpio
PORTVERSION=	1.78
CATEGORIES=	comms python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Raspberry pi gpio module

LICENSE=	UNLICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
