# Created by: Peter Cornelius <pcc@gmx.net>
# $FreeBSD$

PORTNAME=	rpi.gpio2
PORTVERSION=	0.3.0a3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
#RPi.GPIO2-0.3.0a3-py3-none-any.whl
#DISTVERSIONSUFFIX=	-py3-none-any
DISTVERSIONSUFFIX=	-py3-none-any.whl
#EXTRACT_SUFX=	.whl
EXTRACT_SUFX=	
DISTNAME=	RPi.GPIO2-${DISTVERSION}${DISTVERSIONSUFFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Compatibility layer between rpi.gpio syntax and libgpiod semantics

# LICENSE=	 # Ensure this is valid! See ${PORTSDIR}/Mk/bsd.licenses.db.mk.

USES=		python:3.0+ # 3, 3, 3.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
