# Created by: Peter Cornelius <pcc@gmx.net>
# $FreeBSD$

PORTNAME=	fbsd_gpio
PORTVERSION=	0.5.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	Cffi-based python bindings for freebsd gpio

LICENSE=	BSD	# Derived from setup.py

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
