PORTNAME=	arduino-serial-monitor
DISTVERSIONPREFIX=	v
DISTVERSION=	0.15.0
CATEGORIES=	devel

MAINTAINER=	pcc@gmx.net
COMMENT=	Serial pluggable monitor tool for arduino-cli
WWW=		https://github.com/arduino/serial-monitor

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		go:modules
GO_MODULE=	github.com/arduino/serial-monitor

PLIST_FILES=	bin/arduino-serial-monitor

.include <bsd.port.mk>
