# Created by: Peter Cornelius <pcc@gmx.net>
# $FreeBSD$

PORTNAME=	adafruit-ssd1306
PORTVERSION=	1.6.2
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Adafruit_SSD1306-${DISTVERSIONPREFIX}${DISTVERSION}${DISTVERSIONSUFFIX}

MAINTAINER=	pcc@gmx.net
COMMENT=	(Deprecated) Python library to use ssd1306-based 128x64 or 128x32 pixel oled displays with a raspberry pi or beaglebone black

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
